### ISSUE TITLE
Adicionar branch 9.5 - dev 

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/datainjection#1]
![2021-08-16_11-52](https://user-images.githubusercontent.com/86842154/129583716-0d50cfaf-9bbd-4ecf-9ee8-e93d2edd87fb.png)

![2021-08-16_11-52_1](https://user-images.githubusercontent.com/86842154/129583741-3184da80-7007-4fd0-ac8e-ca21ee405222.png)

**Comment by verdanatech-luana** [comment]
Branch 9.5 - dev criada 

![2021-08-16_12-24](https://user-images.githubusercontent.com/86842154/129588620-007cf032-595b-4973-928e-f8fc83f3df42.png)

![2021-08-16_12-25](https://user-images.githubusercontent.com/86842154/129588651-a9cad988-34a3-494f-a420-7cf812ee63b8.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente no GLPI - 9.5.
![TesteDI](https://user-images.githubusercontent.com/80538863/129725385-0fbc6cc8-7952-4c0a-98ae-a15f6936e37e.png)
